const PathConstants = {
  Root: '/',
  DocList: '/docList',
  DocListWaitForMe: 'waitForMe',
  DocListWaitForOthers: 'waitForOthers',
  DocListFinished: 'finished',
  DocListClosed: 'closed',
  DocListDraft: 'draft',
  OrganRnInfo: '/organRnInfo',
  OrganRnBank: '/organRnBank',
  OrganRnFinish: '/organRnFinish',
  SignPwd: '/signPwd',
  SignPwdReset: '/signPwdReset',
  SignPwdResetBySQ: '/signPwdResetBySQ',
  PersonRnInfo: '/personRnInfo',
  PersonRnBank: '/personRnBank',
  PersonRnFinish: '/personRnFinish',
  SealManage: '/sealManage',
  SealCreate: '/sealCreate',
  SealCreateHand: '/sealCreateHand',
  SealHandPreview: '/sealHandPreview',
  SignDoc: '/signDoc',
  DocView: '/docView',
};

export default PathConstants;
